CREATE DATABASE library;
USE library;

CREATE TABLE Khach_Hang(
Ma_KH VARCHAR(10) PRIMARY KEY,
Ten_KH VARCHAR(30),
Dia_Chi VARCHAR(80),
Ngay_Dang_Ki DATE
);

CREATE TABLE Sach(
Ma_ISBN VARCHAR(25) PRIMARY KEY,
Ten_Sach VARCHAR(80),
The_Loai VARCHAR(30),
Gia_Thue DECIMAL (10,2),
Tinh_Trang VARCHAR(3) CHECK (Tinh_Trang IN ('YES', 'NO')),
Tac_Gia VARCHAR(30),
NXB VARCHAR(30)
);

CREATE TABLE Chi_Nhanh(
Ma_CN VARCHAR(10) PRIMARY KEY,
Ma_Quan_Ly VARCHAR(10),
Dia_Chi VARCHAR(80),
SDT VARCHAR(15)
FOREIGN KEY Ma_Quan_Ly REFERENCES Nhan_Vien(Ma_NV)
);

ALTER TABLE Chi_Nhanh
ADD CONSTRAINT Ma_Quan_Ly
FOREIGN KEY (Ma_Quan_Ly) REFERENCES Nhan_Vien(Ma_NV) ON DELETE SET NULL;

CREATE TABLE Nhan_Vien(
Ma_NV VARCHAR(10) PRIMARY KEY,
Ten_NV VARCHAR(30),
Chuc_Vu VARCHAR(30),
Luong DECIMAL (10,2),
Ma_CN VARCHAR(10),
Ma_Quan_Ly VARCHAR(10)
);

CREATE TABLE Sach_Copies(
Ma_Vach VARCHAR(10) PRIMARY KEY,
Ma_ISBN VARCHAR(25),
Ma_CN VARCHAR(10),
Tinh_Trang NVARCHAR(50) DEFAULT 'Moi',
Trang_Thai VARCHAR(15) CHECK (Trang_Thai IN('San Co', 'Dang Muon', 'Bao Tri'))
FOREIGN KEY (Ma_ISBN) REFERENCES Sach(Ma_ISBN),
FOREIGN KEY (Ma_CN) REFERENCES Chi_Nhanh(Ma_CN)
);

CREATE TABLE Phieu_Muon(
Ma_PM INT IDENTITY(1,1) PRIMARY KEY,
Ma_KH VARCHAR(10),
Ma_Vach VARCHAR(10),
Ngay_Muon DATE,
FOREIGN KEY (Ma_KH) REFERENCES Khach_Hang(Ma_KH) ON DELETE CASCADE,
FOREIGN KEY (Ma_Vach) REFERENCES Sach_Copies(Ma_Vach) ON DELETE CASCADE
);

CREATE TABLE Phieu_Tra(
Ma_PT INT IDENTITY(1,1) PRIMARY KEY,
Ma_KH VARCHAR(10),
Ma_Vach VARCHAR(10),
Ngay_Tra DATE,
FOREIGN KEY (Ma_KH) REFERENCES Khach_Hang(Ma_KH) ON DELETE CASCADE,
FOREIGN KEY (Ma_Vach) REFERENCES Sach_Copies(Ma_Vach) ON DELETE CASCADE
);

CREATE TABLE Phieu_Phat(
Ma_PP INT IDENTITY(1,1) PRIMARY KEY,
Ma_PT INT,
Tien_Phat DECIMAL(10,2),
Ly_Do NVARCHAR(100),
Thanh_Toan NVARCHAR(20) CHECK(Thanh_Toan IN('Da Nop', 'Chua Nop')),
FOREIGN KEY (Ma_PT) REFERENCES Phieu_Tra(Ma_PT) ON DELETE CASCADE
);

